import path from 'node:path'
import { promises as fs } from 'node:fs'
import type { GeneratedArticle } from './article-types'

export async function writeGeneratedArticles(
  outputPath: string,
  articles: GeneratedArticle[],
) {
  const generatedCode = `// This file is auto-generated by scripts/generate-thumbnails.tsx
// Do not edit manually.

export type TocItem = {
  id: string;
  text: string;
  depth: 1;
};

export type Article = {
  slug: string;
  title: string;
  description: string;
  date: string;
  tags: string[];
  pin: boolean;
  thumbnail: string;
  body: string;
  html: string;
  toc: TocItem[];
  readingTime: number;
};

export const articles: Article[] = ${JSON.stringify(articles, null, 2)} as const;
`

  await fs.mkdir(path.dirname(outputPath), { recursive: true })
  await fs.writeFile(outputPath, generatedCode)
}
