import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";
import { ProjectFrontmatterSchema } from "./lib/project-schema";
import type { ProjectStatus } from "./lib/project-schema";

type Project = {
  slug: string;
  title: string;
  description: string;
  category: string;
  status: ProjectStatus;
  date: string;
  stack: string[];
  repo?: string;
  link?: string;
  featured: boolean;
};

const rootDir = process.cwd();
const projectsDir = path.join(rootDir, "src/content/projects");
const generatedDir = path.join(rootDir, "src/generated");
const outputPath = path.join(generatedDir, "projects.ts");

function toSlug(filename: string) {
  return filename.replace(/\.mdx?$/, "");
}

async function main() {
  await mkdir(generatedDir, { recursive: true });

  const files = await readdir(projectsDir);
  const markdownFiles = files.filter((file) => file.endsWith(".md"));

  const projects: Project[] = [];

  for (const file of markdownFiles) {
    const filePath = path.join(projectsDir, file);
    const raw = await readFile(filePath, "utf-8");
    const { data } = matter(raw);
    const parsed = ProjectFrontmatterSchema.safeParse(data);

    if (!parsed.success) {
      console.error(`${file} due to invalid project frontmatter:`, parsed.error);
      process.exit(1);
    }

    const frontmatter = parsed.data;

    const slug = toSlug(file);
    projects.push({
      slug,
      title: frontmatter.title,
      description: frontmatter.description,
      category: frontmatter.category,
      status: frontmatter.status,
      date: frontmatter.date,
      stack: frontmatter.stack,
      repo: frontmatter.repo,
      link: frontmatter.link,
      featured: frontmatter.featured,
    });
  }

  projects.sort((a, b) => {
    if (Number(b.featured) !== Number(a.featured)) {
      return Number(b.featured) - Number(a.featured);
    }

    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  const code = `// This file is auto-generated by scripts/generate-projects.ts.
// Do not edit manually.

export type ProjectStatus =
  | "running"
  | "planning"
  | "archived";

export type Project = {
  slug: string;
  title: string;
  description: string;
  category: string;
  status: ProjectStatus;
  date: string;
  stack: string[];
  repo?: string;
  link?: string;
  featured: boolean;
};

export const projects: Project[] = ${JSON.stringify(projects, null, 2)};
`;

  await writeFile(outputPath, code, "utf-8");

  console.log(`Generated ${projects.length} projects.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
