import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import matter from "gray-matter";

type ProjectStatus = "running" | "planning" | "archived";

type ProjectFrontmatter = {
  title?: string;
  description?: string;
  category?: string;
  status?: ProjectStatus;
  date?: string;
  stack?: string[];
  repo?: string;
  link?: string;
  featured?: boolean;
};

type Project = {
  slug: string;
  title: string;
  description: string;
  category: string;
  status: ProjectStatus;
  date: string;
  stack: string[];
  repo?: string;
  link?: string;
  featured: boolean;
};

const rootDir = process.cwd();
const projectsDir = path.join(rootDir, "src/content/projects");
const generatedDir = path.join(rootDir, "src/generated");
const outputPath = path.join(generatedDir, "projects.ts");

function toSlug(filename: string) {
  return filename.replace(/\.mdx?$/, "");
}

function isProjectStatus(value: unknown): value is ProjectStatus {
  return (
    value === "running" ||
    value === "planning" ||
    value === "archived"
  );
}

function optionalString(value: unknown) {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

async function main() {
  await mkdir(generatedDir, { recursive: true });

  const files = await readdir(projectsDir);
  const markdownFiles = files.filter((file) => file.endsWith(".md"));

  const projects: Project[] = [];

  for (const file of markdownFiles) {
    const filePath = path.join(projectsDir, file);
    const raw = await readFile(filePath, "utf-8");
    const { data } = matter(raw);

    const frontmatter = data as ProjectFrontmatter;

    const slug = toSlug(file);
    const status = isProjectStatus(frontmatter.status)
      ? frontmatter.status
      : "running";

    projects.push({
      slug,
      title: frontmatter.title ?? slug,
      description: frontmatter.description ?? "",
      category: frontmatter.category ?? "other",
      status,
      date: frontmatter.date ?? "1970-01-01",
      stack: Array.isArray(frontmatter.stack) ? frontmatter.stack : [],
      repo: optionalString(frontmatter.repo),
      link: optionalString(frontmatter.link),
      featured: frontmatter.featured ?? false,
    });
  }

  projects.sort((a, b) => {
    if (Number(b.featured) !== Number(a.featured)) {
      return Number(b.featured) - Number(a.featured);
    }

    return new Date(b.date).getTime() - new Date(a.date).getTime();
  });

  const code = `// This file is auto-generated by scripts/generate-projects.ts.
// Do not edit manually.

export type ProjectStatus =
  | "running"
  | "planning"
  | "archived";

export type Project = {
  slug: string;
  title: string;
  description: string;
  category: string;
  status: ProjectStatus;
  date: string;
  stack: string[];
  repo?: string;
  link?: string;
  featured: boolean;
};

export const projects: Project[] = ${JSON.stringify(projects, null, 2)};
`;

  await writeFile(outputPath, code, "utf-8");

  console.log(`Generated ${projects.length} projects.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
